name: Deploy Workers

on:
  push:
    branches: [main]
    paths:
      - 'workers/**'

permissions:
  contents: read

jobs:
  deploy-updates-worker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workers
    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
      - uses: cloudflare/wrangler-action@a61fbea3226347cc885c6d1b26b3f47b48e6c0f8
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: workers
